[package]
name = "temperature-converter"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.5", features = ["json", "blocking"] }
getopts = "0.2"
serde = { version = "1.0.207", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }